sudo: false

language: cpp

compiler:
  - clang

script:
  - git submodule init
  - git submodule update
  - mkdir -p build
  - cd build
  - cmake -D RUN_TESTS=ON ..
  - make -j4
  - make test

branches:
  only:
    - cleanup
os:
  - linux
