sudo: false

language: cpp

compiler:
  - clang

script:
  - git submodule init
  - git submodule update
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j4

branches:
  only:
    - cleanup
os:
  - linux
  - osx